const actionTypes = {
    CART_ADD_ITEM: 'CART_ADD_ITEM',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
    CART_SET_SORT: 'CART_SET_SORT',
    CART_SUBMIT: 'CART_SUBMIT',
    CART_SUBMIT_SUCCESS: 'CART_SUBMIT_SUCCESS',
    CART_SUBMIT_FAIL: 'CART_SUBMIT_FAIL',
    PRODUCTS_LOAD: 'PRODUCTS_LOAD'

};

export default actionTypes;